;;; PLL module for Tang Nano 9K: 27MHz -> 48MHz
;;; Uses Gowin rPLL primitive

(in-package :fab)

(fab
 (module pll-48mhz
   :ports ((clk-27mhz :input)
           (clk-48mhz :output)
           (locked :output))
   :signals ((clkout :wire)
             (locked-w :wire)
             (gw-gnd :wire)
             (clkoutp :wire)
             (clkoutd :wire)
             (clkoutd3 :wire))
   :assigns ((gw-gnd 0)
             (clk-48mhz clkout)
             (locked locked-w))
   :body
   ((instance "rPLL" (u-pll) ()
      ((clkout clkout)
       (lock locked-w)
       (clkoutp clkoutp)
       (clkoutd clkoutd)
       (clkoutd3 clkoutd3)
       (reset gw-gnd)
       (reset-p gw-gnd)
       (clkin clk-27mhz)
       (clkfb gw-gnd)
       (fbdsel (concat gw-gnd gw-gnd gw-gnd gw-gnd gw-gnd gw-gnd))
       (idsel (concat gw-gnd gw-gnd gw-gnd gw-gnd gw-gnd gw-gnd))
       (odsel (concat gw-gnd gw-gnd gw-gnd gw-gnd gw-gnd gw-gnd))
       (psda (concat gw-gnd gw-gnd gw-gnd gw-gnd))
       (dutyda (concat gw-gnd gw-gnd gw-gnd gw-gnd))
       (fdly (concat gw-gnd gw-gnd gw-gnd gw-gnd))))
    (defparam u-pll.fclkin "27")
    (defparam u-pll.dyn-idiv-sel "false")
    (defparam u-pll.idiv-sel 8)
    (defparam u-pll.dyn-fbdiv-sel "false")
    (defparam u-pll.fbdiv-sel 15)
    (defparam u-pll.dyn-odiv-sel "false")
    (defparam u-pll.odiv-sel 9)
    (defparam u-pll.psda-sel "0000")
    (defparam u-pll.dyn-da-en "true")
    (defparam u-pll.dutyda-sel "1000")
    (defparam u-pll.clkout-ft-dir 1)
    (defparam u-pll.clkoutp-ft-dir 1)
    (defparam u-pll.clkout-dly-step 0)
    (defparam u-pll.clkoutp-dly-step 0)
    (defparam u-pll.clkfb-sel "internal")
    (defparam u-pll.clkout-bypass "false")
    (defparam u-pll.clkoutp-bypass "false")
    (defparam u-pll.clkoutd-bypass "false")
    (defparam u-pll.dyn-sdiv-sel 2)
    (defparam u-pll.clkoutd-src "CLKOUT")
    (defparam u-pll.clkoutd3-src "CLKOUT"))))
