(in-package :fab)

(fab
 (module usbfs-core-top
  :depends (usbfs-bitlevel usbfs-packet-rx usbfs-packet-tx usbfs-transaction)
  :ports ((rstn :input)
          (clk :input)
          (usb-dp-pull :output 1 :reg)
          (usb-dp :inout)
          (usb-dn :inout)
          (usb-rstn :output 1 :reg)
          (sot :output)
          (sof :output)
          (ep00-setup-cmd :output 64)
          (ep00-resp-idx :output 9)
          (ep00-resp :input 8)
          (ep81-data :input 8) (ep81-valid :input) (ep81-ready :output)
          (ep82-data :input 8) (ep82-valid :input) (ep82-ready :output)
          (ep83-data :input 8) (ep83-valid :input) (ep83-ready :output)
          (ep84-data :input 8) (ep84-valid :input) (ep84-ready :output)
          (ep01-data :output 8) (ep01-valid :output)
          (ep02-data :output 8) (ep02-valid :output)
          (ep03-data :output 8) (ep03-valid :output)
           (ep04-data :output 8) (ep04-valid :output))

  :params ((descriptor-device 0)
           (descriptor-str1 0)
           (descriptor-str2 0)
           (descriptor-str3 0)
           (descriptor-str4 0)
           (descriptor-str5 0)
           (descriptor-str6 0)
           (descriptor-config 0)
           (ep00-maxpktsize #x20)
           (ep81-maxpktsize #x20)
           (ep82-maxpktsize #x20)
           (ep83-maxpktsize #x20)
           (ep84-maxpktsize #x20)
           (ep81-isochronous 0)
           (ep82-isochronous 0)
           (ep83-isochronous 0)
           (ep84-isochronous 0)
           (ep01-isochronous 0)
           (ep02-isochronous 0)
           (ep03-isochronous 0)
           (ep04-isochronous 0)
           (debug "FALSE"))

  :localparams ((reset-cycles 120000000))

  :signals ((usb-oe :wire)
            (usb-dp-tx :wire)
            (usb-dn-tx :wire)
            (rx-sta :wire)
            (rx-ena :wire)
            (rx-bit :wire)
            (rx-fin :wire)
            (tx-sta :wire)
            (tx-req :wire)
            (tx-bit :wire)
            (tx-fin :wire)
            (rp-pid :wire 4)
            (rp-addr :wire 11)
            (rp-byte-en :wire)
            (rp-byte :wire 8)
            (rp-fin :wire)
            (rp-okay :wire)
            (tp-sta :wire)
            (tp-pid :wire 4)
            (tp-byte-req :wire)
            (tp-byte :wire 8)
            (tp-fin-n :wire)
            (usb-rstn-cnt :reg 32))

  :assigns ((usb-dp (if usb-oe usb-dp-tx (high-z)))
            (usb-dn (if usb-oe usb-dn-tx (high-z))))

  :body
  ((always
      (posedge clk)
    (if (not rstn)
      (begin
        (setf-nb usb-dp-pull 0)
        (setf-nb usb-rstn 0)
        (setf-nb usb-rstn-cnt 0))
      (begin
        (if (< usb-rstn-cnt reset-cycles)
          (begin
            (setf-nb usb-dp-pull 0)
            (setf-nb usb-rstn 0)
            (setf-nb usb-rstn-cnt (+ usb-rstn-cnt 1)))
          (if (/= usb-dp usb-dn)
            (begin
              (setf-nb usb-dp-pull 1)
              (setf-nb usb-rstn 1)
              (setf-nb usb-rstn-cnt (+ reset-cycles 300)))
            (if (> usb-rstn-cnt reset-cycles)
              (begin
                (setf-nb usb-dp-pull 1)
                (setf-nb usb-rstn 1)
                (setf-nb usb-rstn-cnt (- usb-rstn-cnt 1)))
              (begin
                (setf-nb usb-dp-pull 1)
                (setf-nb usb-rstn 0))))))))

   ;; bit-level
   (instance usbfs-bitlevel (u-usbfs-bitlevel) ()
     ((rstn usb-rstn)
      (clk clk)
      (usb-oe usb-oe)
      (usb-dp-tx usb-dp-tx)
      (usb-dn-tx usb-dn-tx)
      (usb-dp-rx usb-dp)
      (usb-dn-rx usb-dn)
      (rx-sta rx-sta)
      (rx-ena rx-ena)
      (rx-bit rx-bit)
      (rx-fin rx-fin)
      (tx-sta tx-sta)
      (tx-req tx-req)
      (tx-bit tx-bit)
      (tx-fin tx-fin)))

   ;; packet RX
   (instance usbfs-packet-rx (u-usbfs-packet-rx) ()
     ((rstn usb-rstn)
      (clk clk)
      (rx-sta rx-sta)
      (rx-ena rx-ena)
      (rx-bit rx-bit)
      (rx-fin rx-fin)
      (rp-pid rp-pid)
      (rp-addr rp-addr)
      (rp-byte-en rp-byte-en)
      (rp-byte rp-byte)
      (rp-fin rp-fin)
      (rp-okay rp-okay)))

   ;; packet TX
   (instance usbfs-packet-tx (u-usbfs-packet-tx) ()
     ((rstn usb-rstn)
      (clk clk)
      (tp-sta tp-sta)
      (tp-pid tp-pid)
      (tp-byte-req tp-byte-req)
      (tp-byte tp-byte)
      (tp-fin-n tp-fin-n)
      (tx-sta tx-sta)
      (tx-req tx-req)
      (tx-bit tx-bit)
      (tx-fin tx-fin)))

   ;; transaction level
   (instance usbfs-transaction (u-usbfs-transaction)
     ((descriptor-device descriptor-device)
      (descriptor-str1 descriptor-str1)
      (descriptor-str2 descriptor-str2)
      (descriptor-str3 descriptor-str3)
      (descriptor-str4 descriptor-str4)
      (descriptor-str5 descriptor-str5)
      (descriptor-str6 descriptor-str6)
      (descriptor-config descriptor-config)
      (ep00-maxpktsize ep00-maxpktsize)
      (ep81-maxpktsize ep81-maxpktsize)
      (ep82-maxpktsize ep82-maxpktsize)
      (ep83-maxpktsize ep83-maxpktsize)
      (ep84-maxpktsize ep84-maxpktsize)
      (ep81-isochronous ep81-isochronous)
      (ep82-isochronous ep82-isochronous)
      (ep83-isochronous ep83-isochronous)
      (ep84-isochronous ep84-isochronous)
      (ep01-isochronous ep01-isochronous)
      (ep02-isochronous ep02-isochronous)
      (ep03-isochronous ep03-isochronous)
      (ep04-isochronous ep04-isochronous))
     ((rstn usb-rstn)
      (clk clk)
      (rp-pid rp-pid)
      (rp-endp (slice rp-addr 10 7))
      (rp-byte-en rp-byte-en)
      (rp-byte rp-byte)
      (rp-fin rp-fin)
      (rp-okay rp-okay)
      (tp-sta tp-sta)
      (tp-pid tp-pid)
      (tp-byte-req tp-byte-req)
      (tp-byte tp-byte)
      (tp-fin-n tp-fin-n)
      (sot sot)
      (sof sof)
      (ep00-setup-cmd ep00-setup-cmd)
      (ep00-resp-idx ep00-resp-idx)
      (ep00-resp ep00-resp)
      (ep81-data ep81-data)
      (ep81-valid ep81-valid)
      (ep81-ready ep81-ready)
      (ep82-data ep82-data)
      (ep82-valid ep82-valid)
      (ep82-ready ep82-ready)
      (ep83-data ep83-data)
      (ep83-valid ep83-valid)
      (ep83-ready ep83-ready)
      (ep84-data ep84-data)
      (ep84-valid ep84-valid)
      (ep84-ready ep84-ready)
      (ep01-data ep01-data)
      (ep01-valid ep01-valid)
      (ep02-data ep02-data)
      (ep02-valid ep02-valid)
      (ep03-data ep03-data)
      (ep03-valid ep03-valid)
      (ep04-data ep04-data)
      (ep04-valid ep04-valid))))))
